### ISSUE TITLE
Add a vignette about AQI

### ISSUE THREAD

**Issue by maelle** [ropensci/ropenaq#11]
Motivation: offering comparison of different AQI definitions

Input: the right measurements (table with hour, value pollutant 1, value pollutant 2, etc) and the argument "version" for choosing the AQI definition.

Only those for which all parameters are available on the platform (or with breakpoints for individual pollutants like the Indian AQI).

Canada: https://en.wikipedia.org/wiki/Air_Quality_Health_Index_(Canada) O3, NO2, PM2.5

Mexico: https://es.wikipedia.org/wiki/%C3%8Dndice_Metropolitano_de_la_Calidad_del_Aire ozono (O3), partículas menores a 10 micrómetros (PM10), partículas menores a 2.5 micrómetros (PM2.5) dióxido de azufre (SO2), dióxido de nitrógeno (NO2) y monóxido de carbono (CO)

India: the platform does not have all pollutants, but possible to give breakpoints for individual pollutants although it's less interesting

UK: https://en.wikipedia.org/wiki/Air_quality_index#United_Kingdom Ozone, Nitrogen Dioxide, Sulphur Dioxide, PM2.5 (particles with an aerodynamic diameter less than 2.5 μm) and PM10.

**Comment by masalmon** [comment]
Need to be careful about different aggregation levels for different pollutants in some definitions.

When reading input table, first check whether the data has the right columns for the AQI definitions (e.g. need O3 for Canada definition), and the right time aggregation.

**Comment by masalmon** [comment]
Goal: convert (near) all https://en.wikipedia.org/wiki/Air_quality_index to code.

**Comment by masalmon** [comment]
Now I rather think this should be a vignette.

**Comment by masalmon** [comment]
or even better, a separate "aqi" package which could have ropenaq as a suggests dependency for building a vignette.

**Comment by masalmon** [comment]
The idea would be to have a vignette e.g. producing graphs like https://twitter.com/UrbanEmissions/status/823708234410119168
