### ISSUE TITLE
add api-fetch and use it for making a nice animated visualization

### ISSUE THREAD

**Issue by maelle** [ropensci/ropenaq#14]
https://docs.openaq.org/#api-Fetches

(although I have no idea what the use of these data is -> it must be useful)

**Comment by jflasher** [comment]
@masalmon I wouldn't worry so much about adding this. It's very useful information as it shows you how much data is getting added for each source and if there are issues when trying to get the data. However, not sure if it's something that would be widely used in this package. So probably not something urgent to add.

**Comment by masalmon** [comment]
Ok, anyway I have to solve a more urgent issue. What do you think would be an use case? Something showing how much data is being added at a given moment? Like a visualization of the dynamics of the API?

**Comment by jflasher** [comment]
Yeah, you could do something like that. Main intended usage is really as a 'health check.' It'll show you how often a location is getting new data.

**Comment by masalmon** [comment]
I need to give it some thought but I'd love to find a way to visualize OpenAQ's beating heart. I could e.g. draw a map of Delhi's stations and have hearts whose size depends on the number of measurements added and with time as frame, for getting a nice animation...

**Comment by masalmon** [comment]
(looking at such an animation = literally a health check!)
