### ISSUE TITLE
crul

### ISSUE THREAD

**Issue by maelle** [ropensci/ropenaq#28]
* Step 1: Get rid of `httr` in favor of `crul`. DONE

* Step 2: Add async for the measurements endpoint. DONE

Branch crul

**Comment by masalmon** [comment]
Add doc and tests

**Comment by masalmon** [comment]
Use `AsyncVaried`

```r
req1 <- HttpRequest$new(url = "https://httpbin.org/get")$get(query = list(page = 1))
req2 <- HttpRequest$new(url = "https://httpbin.org/get")$get(query = list(page = 2))
res <- AsyncVaried$new(req1, req2)
res$request()
```

**Comment by maelle** [comment]
check status and retry if needed

**Comment by maelle** [comment]
The code for checking for status could be modularized more.

**Comment by maelle** [comment]
But modularizing this code is no priority for me.
