### ISSUE TITLE
fail to get information by city limit

### ISSUE THREAD

**Issue by Ljinghua** [ropensci/ropenaq#31]
I have a question about how to get the information by city/location limit. I can not get the information of those city/location which has a "space" like MEXICO STATE.

resM <- aq_measurements(city = "MEXICO+STATE",parameter = "pm25", date_from = "2017-03-01", date_to = "2017-03-31", limit = 10000)

It will give me this error, and if I write "MEXICO STATE" there is not this combination.
Error in cbind_all(x) : not compatible with STRSXP

**Comment by maelle** [comment]
@Ljinghua thanks for the bug report! I've just pushed what I think could be a fix. 

Can you install the development version via `devtools::install_github(ropensci/ropenaq)` for instance and tell me if it works for you?

**Comment by Ljinghua** [comment]
Thanks a lot !!! It works and I also need install two packages more for installing the development version 
They are :
install.packages("stringr")
install.packages("urltools")

Thanks again .

**Comment by maelle** [comment]
@Ljinghua well really thank *you*, I am very grateful that you found and reported the bug. :smile_cat:

**Comment by maelle** [comment]
@Ljinghua for info there's now a new `ropenaq` version on CRAN corresponding to the version I made you install. Thanks again for the bug report!
