### ISSUE TITLE
fail to get pm10 in Ulaanbaatar

### ISSUE THREAD

**Issue by Ljinghua** [ropensci/ropenaq#32]
Hello,
    I get another question about getting the pm10 data of the station "100+ail" of Ulaanbaatar. It returns this error "  Error in cbind_all(x) : not compatible with STRSXP".
   However, there is no problem in getting the no2 data for the same station.
 Thanks

num=as.numeric(Ula_location_pm10[1,"count"])
 for (page in 1:ceiling(num/1000)){
 Ula_pm25 <- rbind(Ula_pm10,
 aq_measurements(city = "Ulaanbaatar", parameter = "pm10", location="100+ail",  
                    date_from = "2015-09-01", date_to = "2017-04-27",
                    limit = 1000, page = page))
 }
Error in cbind_all(x) : not compatible with STRSXP

**Comment by maelle** [comment]
Thanks for the report!

For which page do you get this error?

Do you know that if you don't write page, you don't need to loop, the package will loop for you?

```r
aq_measurements(city = "Ulaanbaatar", parameter = "pm10", 
                location="100+ail",
                date_from = "2015-09-01", 
                date_to = "2015-11-27",
                limit = 1000)
```

would get you all measurements available from 2015-09-01 to 2015-11-27 for instance.

**Comment by maelle** [comment]
This worked for me to get all the data for the period you mention:

```r
lala <- aq_measurements(city = "Ulaanbaatar", parameter = "pm10", 
                location="100+ail",
                date_from = "2015-09-01", 
                date_to = "2017-04-27",
                limit = 1000)
```

I get 49,863 measurements.

**Comment by maelle** [comment]
There's a mistake in your code example I think 😉 it's not the reason for the bug I guess but you write Ula_pm25 instead of Ula_pm10.

**Comment by Ljinghua** [comment]
That´s TRUE!!!!!!!!!!!!!!!!!Sorry for the stupid mistake, I just couldnt find out it .

thanks a lot

**Comment by maelle** [comment]
No problem at all! I do similar mistakes too, welcome to the club :sunglasses: 

With the last code I posted you can get data without a loop, I guess it's easier + it means there's less copy-paste to do hence less room for mistakes :wink:

**Comment by maelle** [comment]
If it works for you I'll close the issue.

**Comment by Ljinghua** [comment]
yes it works for me, thanks again.

**Comment by maelle** [comment]
awesome!
